apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysql-service
  name: mysql-service
spec:
  ports:
  - name: mysql-port
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-db
  type: ClusterIP
status:
  loadBalancer: {}
